"""Markdown renderer — the default, token-efficient map.

Two sections: a directory **Tree** (noisy dirs collapsed) and a **Symbols**
breakdown (signatures only, methods nested under their class). The header
carries the hero token-savings line. Callables render as ``name(params) -> ret``
with no language keyword — the parens make the kind obvious and save tokens;
classes and other declarations are tagged with their kind word.
"""

from __future__ import annotations

from ..model import DirNode, FileEntry, ProjectMap, Symbol

_DOC_MAX = 80
_CALLABLE = frozenset({"function", "method"})
_CLASSLIKE = frozenset(
    {"class", "struct", "interface", "enum", "trait", "impl", "module", "record", "type"}
)


def render(project: ProjectMap, headline: str) -> str:
    lines: list[str] = []
    lines.append(f"# 🌳 {project.root_name} — Project Map")
    lines.append("")
    lines.append(f"> **{headline}**")
    lines.append(">")
    lines.append("> Signatures only — no function bodies. Generated by `skeletree`.")
    if project.truncated:
        lines.append(f">  \n> ⚠️ {project.truncated} files omitted (max-files limit).")
    lines.append("")

    lines.append("## Tree")
    lines.append("")
    lines.append("```text")
    lines.extend(_tree_lines(project.tree) if project.tree else [])
    lines.append("```")
    lines.append("")

    files_with_symbols = [f for f in project.files if f.symbols]
    if files_with_symbols:
        lines.append("## Symbols")
        lines.append("")
        for entry in files_with_symbols:
            lines.extend(_file_section(entry))

    return "\n".join(lines).rstrip() + "\n"


# --- tree ------------------------------------------------------------------


def _tree_lines(root: DirNode) -> list[str]:
    lines = [f"{root.name}/"]
    _walk_tree(root, 1, lines)
    return lines


def _walk_tree(node: DirNode, depth: int, lines: list[str]) -> None:
    indent = "  " * depth
    for child in node.children:
        if child.is_dir:
            collapsed = _collapsed_child(child)
            if collapsed is not None:
                lines.append(f"{indent}{child.name}/ ({collapsed} files)")
            else:
                lines.append(f"{indent}{child.name}/")
                _walk_tree(child, depth + 1, lines)
        elif not child.collapsed_count:
            lines.append(f"{indent}{child.name}")


def _collapsed_child(node: DirNode) -> int | None:
    if len(node.children) == 1 and node.children[0].collapsed_count:
        return node.children[0].collapsed_count
    return None


# --- symbols ---------------------------------------------------------------


def _file_section(entry: FileEntry) -> list[str]:
    lines = [f"### `{entry.path}` · {entry.language}", ""]
    for sym in entry.symbols:
        _render_symbol(sym, 0, lines)
    lines.append("")
    return lines


def _render_symbol(sym: Symbol, depth: int, lines: list[str]) -> None:
    indent = "  " * depth
    lines.append(f"{indent}- {_symbol_text(sym)}")
    for child in sym.children:
        _render_symbol(child, depth + 1, lines)


def _symbol_text(sym: Symbol) -> str:
    deco = "".join(f"@{d} " for d in sym.decorators)
    body = _declaration(sym)
    text = f"{deco}`{body}`"
    if sym.doc:
        text += f" — {_clip(sym.doc)}"
    return text


def _declaration(sym: Symbol) -> str:
    sig = sym.signature
    if sym.kind in _CALLABLE:
        prefix = ""
        if sig.startswith("async "):  # python async marker, see python_ast
            prefix, sig = "async ", sig[len("async ") :]
        return f"{prefix}{sym.name}{sig}"
    if sym.kind in _CLASSLIKE:
        return f"{sym.kind} {sym.name}{sig}"
    # const / static / field / var: kind word + name + optional ": type"
    return f"{sym.kind} {sym.name}{sig}"


def _clip(text: str) -> str:
    text = text.strip()
    if len(text) <= _DOC_MAX:
        return text
    return text[: _DOC_MAX - 1].rstrip() + "…"
